spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DB}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      auto-index-creation: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://dev-mytwin-eureka-service/eureka/
  instance:
    preferIpAddress: true


graph:
  api:
    base-url: https://graph.microsoft.com.rproxy.goskope.com/v1.0
    me-url: /me
    direct-reports-url: /me/directReports
    photo-value-url:   /me/photo/$value