spring:
  data:
    mongodb:
      host: ${UAT_MONGODB_HOST}
      port: ${UAT_MONGODB_PORT}
      database: ${UAT_MONGODB_DB}
      username: ${UAT_MONGODB_USERNAME}
      password: ${UAT_MONGODB_PASSWORD}
      auto-index-creation: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://uat-eureka-server:8761/eureka/
  instance:
    preferIpAddress: true