spring:
  data:
    mongodb:
      uri: mongodb://${UAT_MONGODB_USERNAME}:${UAT_MONGODB_PASSWORD}@${UAT_MONGODB_HOST}:${UAT_MONGODB_PORT}/${UAT_MONGODB_DB}?authSource=admin
      auto-index-creation: true
