spring:
  data:
    mongodb:
      uri: mongodb://${PROD_MONGODB_USERNAME}:${PROD_MONGODB_PASSWORD}@${PROD_MONGODB_HOST}:${PROD_MONGODB_PORT}/${PROD_MONGODB_DB}?authSource=admin
      auto-index-creation: true
