spring:
  data:
    mongodb:
      uri: mongodb://${PROD_MONGODB_USERNAME:mytwin}:${PROD_MONGODB_PASSWORD:Mytwin_123}@${PROD_MONGODB_HOST:localhost}:${PROD_MONGODB_PORT:27017}/${PROD_MONGODB_DB:my_twins}?authSource=admin
      auto-index-creation: true
