spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:mytwin}:${MONGODB_PASSWORD:Mytwin_123}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DB:my_twins}?authSource=admin
      auto-index-creation: true
