spring:
  data:
    mongodb:
      host: ${PROD_MONGODB_HOST}
      port:  ${PROD_MONGODB_PORT}
      database:  ${PROD_MONGODB_DATABASE}
      username:  ${PROD_MONGODB_USERNAME}
      password:  ${PROD_MONGODB_PASSWORD}
      auto-index-creation: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://prod-eureka-server:8761/eureka/
  instance:
    preferIpAddress: true